#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2

if [[ -z ${PORTHOS_FIRST_CONFIG} ]]; then
    systemctl --user enable --now fpm.service nginx.service snapshot.timer
    echo 'PORTHOS_FIRST_CONFIG=1' >> environment
else
    systemctl --user try-reload-or-restart fpm.service nginx.service snapshot.timer
fi
