#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

# Restart the service
systemctl --user try-restart fpm.service nginx.service snapshot.timer sync-head.timer
