#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

config = {
    'source': os.environ['PORTHOS_SOURCE'],
    'retention': int(os.environ['PORTHOS_RETENTION']),
    'server_name': os.environ['PORTHOS_SERVER_NAME'],
}

json.dump(config, fp=sys.stdout)